version: '3.8'
services:
  db:
    image: postgres:13.7-alpine
    container_name: shareit-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  server:
    build: ./server
    image: server
    container_name: shareit-srv
    ports:
      - "9090:5050"
    depends_on:
      - db
    environment:
      - SERVER_PORT=5050
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  gateway:
    build: ./gateway
    image: gateway
    container_name: shareit-gw
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:5050